project:
  type: website
  output-dir: _site
  render:
    - "t*.qmd"
    - "u*.qmd"
    - "!sem1/"
    - "sem2/"
    - "sem3/"

execute:
  freeze: auto
  cache: true

format:
  html:
    toc: true
    respect-user-color-scheme: true
    page-navigation: true
    theme:
      light: flatly
      dark: darkly
    mainfont: "IosevkaTerm Nerd Font Mono"
    fontsize: 20px

website:
  title: "My Notes"
  sidebar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/coglinks/notes
          - text: Report an Issue
            href: https://github.com/coglinks/notes/issues
    style: "docked"
    contents:
      - section: "Digital Electronics"
        contents: sems/sem3/dig-elec/*
      - section: "Network Fundamentals"
        contents: sems/sem3/net-fund/*
      - section: "Calculus II"
        contents: sems/sem3/calc-2/*
      - section: "Analog Electronics"
        contents: sems/sem3/ana-elec/*
      - section: "Calculus I"
        contents: sems/sem2/calc1/*
      - section: "Fund. Elec. II"
        contents: sems/sem2/fund-elec2/*
      - section: "course list"
        contents: sems/sem2/class-enroll/*
