project:
  type: website
  output-dir: _site

format:
  html:
    embed-resources: true
    toc: true
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
    mainfont: "IosevkaTerm Nerd Font Mono"
    fontsize: 20px

website:
  title: "My Notes"
  sidebar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/coglinks/notes
          - text: Report an Issue
            href: https://github.com/coglinks/notes/issues
    left:
      - text: "Calculus I"
        menu:
          - href: calc1/index.qmd
          - href: calc1/u1-the-derivative.md
          - href: calc1/u3-transcendental.md
          - href: calc1/u4-.qmd
      - text: "Fund. Elec. II"
        menu:
          - href: fund-elec2/index.qmd
          - href: fund-elec2/doubts.qmd
          - href: fund-elec2/revision.qmd
          - href: fund-elec2/t01-sinusoidal-alternating-waveforms.qmd
          - href: fund-elec2/t02-basic-elements-and-phasors.qmd
          - href: fund-elec2/t03-series-ac-circuits.qmd
          - href: fund-elec2/t04-parallel-ac-circuits.qmd
          - href: fund-elec2/t05-series-parallel-ac-circuits.qmd
          - href: fund-elec2/t06-power(ac).qmd
          - href: fund-elec2/t07-introduction-to-three-phase-systems.qmd
          - href: fund-elec2/t08-resonance-and-filters.qmd
          - href: fund-elec2/t09-methods-of-analysis.qmd
