---
title: '11. Introduction to Magnetic Circuits and Transformers'
---

## Introduction

$\Phi = \frac{\mathcal{F}}{\mathcal{R}}$

Where,

- $Phi$ = electromotive force
- $\mathcal{F}$ = Magnetomotive force (MMF)
- $\mathcal{R}$ = 

## Magnetic Field

Flux density, $B$

- $B = \frac{\Phi}{A}$

Unit:

- $B=\mathrm{Wb/m^2 = T}$ (teslas)
- $\Phi = \text{Wb}$ (webers)
- $A = m^2$

$\mathcal{F} = NI$

Permeability $\mu$

$\mu_r = \frac{\mu_r}

## Reluctance

reluctance is the opposition to the magnetic flux

$\mathcal{R} = \frac{l}{\mu A}$

## Ohm's Law for Magnetic Circuits

$\Phi = \frac{\mathcal{F}}{\mathcal{R}}$

## Magnetizing Force $(H)$

$H = \frac{\mathcal{F}}{l} = \frac{NI}{l}$

$B = \mu H$

## Hysteresis

When you magnetize something and remove the magnetizing force, the material will resist losing its magnetization and will take longer time to lose it than the time it took to gain it

## Ampere's Circuital Law

The algebric sum of the rise and drops of the mmf around a closed loop of a magnetic circuit is zero. This is similar to KVL.

## Air Gaps

$B_g = \frac{Phi_g}{A_g}$

## Applications

##  Transformers

They increase (step up) or decrease (step down) the voltage

The transfer has 2 parts:

- Primary (for the input)
- Secondary (for the output)

It cnsists of a transfer core and 2 coils. It works like so:

- Current flows through the primary coil
- Current flow through the coil induces a changing magnetic field in the transformer core
- The changing magnetic field flows through out the transformer core
- The changing magnetic field in the transformer core induces a voltage and hence a current in the secondary coil

### Mutual Inductance

:::{.callout-warning}
This section is incomplete
:::

$$e_s = N_s \frac{d\phi_m}{dt}$$

- $N_s =$ Number of turn in the secondary coil
- $\phi_m =$ Portion of $\phi_p$ that links with the secondary winding

### Iron Core Transformer

:::{.callout-warning}
This section is incomplete
:::

Transformer ratio: $a = \dfrac{N_p}{N_s}$

$$\frac{V_p}{V_s} = \frac{N_p}{N_s} = \frac{I_s}{I_p}$$

Primary and secondary is reversed for the current since $I \propto \dfrac{1}{N}$

## Rectifier (Complete)

They convert AC to DC
