##  COMM1020

| Class ID | Days and Times | Room | Instructor | Status |
|----------|----------------|------|------------|--------|
| Lecture - Class 2197 -Section 2 | Wednesday<br>12:00PM to 1:00PM<hr>Sunday<br>10:00AM to 12:00PM | 01.2.08<br>10.2.01 | Andrea Comeau<br>Andrea Comeau | open (118-120)<br>open (30-30) |
| Lecture - Class 2198 -Section 3 | Wednesday<br>12:00PM to 1:00PM<hr>Tuesday<br>12:00PM to 2:00PM | 01.2.08<br>12.2.13 | Andrea Comeau<br>Andrea Comeau | open (118-120)<br>open (22-24) |
| Lecture - Class 2199 -Section 4 | Wednesday<br>12:00PM to 1:00PM<hr>Tuesday<br>10:00AM to 12:00PM | 01.2.08<br>10.2.05 | Andrea Comeau<br>Andrea Comeau | open (118-120)<br>open (30-30) |
| Lecture - Class 2200 -Section 5 | Wednesday<br>12:00PM to 1:00PM<hr>Thursday<br>10:00AM to 12:00PM | 01.2.08<br>10.2.05 | Andrea Comeau<br>Andrea Comeau | open (118-120)<br>open (30-30) |
| Lecture - Class 2205 -Section 10 | Sunday<br>6:00PM to 7:00PM<hr>Thursday<br>2:00PM to 4:00PM | 01.1.06<br>10.2.06 | Ridha Ben Rejeb<br>Ridha Ben Rejeb | open (111-120)<br>open (28-30) |
| Lecture - Class 2202 -Section 7 | Sunday<br>6:00PM to 7:00PM<hr>Monday<br>2:00PM to 4:00PM | 01.1.06<br>12.2.10 | Ridha Ben Rejeb<br>Ridha Ben Rejeb | open (111-120)<br>open (30-30) |
| Lecture - Class 2203 -Section 8 | Sunday<br>6:00PM to 7:00PM<hr>Tuesday<br>12:00PM to 2:00PM | 01.1.06<br>05.2.26 | Ridha Ben Rejeb<br>Ridha Ben Rejeb | open (111-120)<br>open (26-30) |
| Lecture - Class 2204 -Section 9 | Sunday<br>6:00PM to 7:00PM<hr>Wednesday<br>2:00PM to 4:00PM | 01.1.06<br>12.1.03 | Ridha Ben Rejeb<br>Ridha Ben Rejeb | open (111-120)<br>open (27-30) |
| Lecture - Class 2211 -Section 16 | Monday<br>12:00PM to 1:00PM<hr>Wednesday<br>2:00PM to 4:00PM | 01.1.06<br>12.2.10 | Irum Naz<br>Irum Naz | open (87-90)<br>open (29-30) |
| Lecture - Class 2212 -Section 17 | Monday<br>12:00PM to 1:00PM<hr>Tuesday<br>12:00PM to 2:00PM | 01.1.06<br>10.1.31 | Irum Naz<br>Irum Naz | open (87-90)<br>open (30-30) |
| Lecture - Class 2213 -Section 18 | Monday<br>12:00PM to 1:00PM<hr>Thursday<br>12:00PM to 2:00PM | 01.1.06<br>10.1.31 | Irum Naz<br>Irum Naz | open (87-90)<br>open (28-30) |
| Lecture - Class 2216 -Section 21 | Tuesday<br>2:00PM to 3:00PM<hr>Wednesday<br>2:00PM to 4:00PM | 01.1.06<br>05.1.66 | Cristina Fabretto<br>Cristina Fabretto | open (117-120)<br>open (30-30) |
| Lecture - Class 2217 -Section 22 | Tuesday<br>2:00PM to 3:00PM<hr>Monday<br>2:00PM to 4:00PM | 01.1.06<br>10.2.01 | Cristina Fabretto<br>Cristina Fabretto | open (117-120)<br>open (29-30) |
| Lecture - Class 2218 -Section 23 | Tuesday<br>2:00PM to 3:00PM<hr>Wednesday<br>4:00PM to 6:00PM | 01.1.06<br>05.1.38 | Cristina Fabretto<br>Cristina Fabretto | open (117-120)<br>open (28-30) |
| Lecture - Class 2220 -Section 25 | Monday<br>4:00PM to 5:00PM<hr>Tuesday<br>2:00PM to 4:00PM | 05.2.44<br>10.2.06 | Shawn Ramsey<br>Shawn Ramsey | open (53-58)<br>open (25-29) |
| Lecture - Class 2221 -Section 26 | Monday<br>4:00PM to 5:00PM<hr>Tuesday<br>4:00PM to 6:00PM | 05.2.44<br>10.2.06 | Shawn Ramsey<br>Shawn Ramsey | open (53-58)<br>open (28-29) |
| Lecture - Class 2227 -Section 32 | Tuesday<br>4:00PM to 5:00PM<hr>Thursday<br>2:00PM to 4:00PM | 12.1.08<br>12.1.03 | Irum Naz<br>Irum Naz | open (60-60)<br>open (30-30) |
| Lecture - Class 2228 -Section 33 | Tuesday<br>4:00PM to 5:00PM<hr>Wednesday<br>4:00PM to 6:00PM | 12.1.08<br>05.2.25 | Irum Naz<br>Irum Naz | open (60-60)<br>open (30-30) |

## PHYS1020 General Physics 

Recommendations:
- Feras Alzubi
- AETN 1102

| Class ID | Days and Times | Room | Instructor | Status |
|----------|----------------|------|------------|--------|
| Lecture - Class 2197 -Section 2 | Wednesday<br>12:00PM to 1:00PM<hr>Sunday<br>10:00AM to 12:00PM | 01.2.08<br>10.2.01 | Andrea Comeau<br>Andrea Comeau | open (118-120)<br>open (30-30) |
| Lecture - Class 2198 -Section 3 | Wednesday<br>12:00PM to 1:00PM<hr>Tuesday<br>12:00PM to 2:00PM | 01.2.08<br>12.2.13 | Andrea Comeau<br>Andrea Comeau | open (118-120)<br>open (22-24) |
| Lecture - Class 2199 -Section 4 | Wednesday<br>12:00PM to 1:00PM<hr>Tuesday<br>10:00AM to 12:00PM | 01.2.08<br>10.2.05 | Andrea Comeau<br>Andrea Comeau | open (118-120)<br>open (30-30) |
| Lecture - Class 2200 -Section 5 | Wednesday<br>12:00PM to 1:00PM<hr>Thursday<br>10:00AM to 12:00PM | 01.2.08<br>10.2.05 | Andrea Comeau<br>Andrea Comeau | open (118-120)<br>open (30-30) |
| Lecture - Class 2205 -Section 10 | Sunday<br>6:00PM to 7:00PM<hr>Thursday<br>2:00PM to 4:00PM | 01.1.06<br>10.2.06 | Ridha Ben Rejeb<br>Ridha Ben Rejeb | open (111-120)<br>open (28-30) |
| Lecture - Class 2202 -Section 7 | Sunday<br>6:00PM to 7:00PM<hr>Monday<br>2:00PM to 4:00PM | 01.1.06<br>12.2.10 | Ridha Ben Rejeb<br>Ridha Ben Rejeb | open (111-120)<br>open (30-30) |
| Lecture - Class 2203 -Section 8 | Sunday<br>6:00PM to 7:00PM<hr>Tuesday<br>12:00PM to 2:00PM | 01.1.06<br>05.2.26 | Ridha Ben Rejeb<br>Ridha Ben Rejeb | open (111-120)<br>open (26-30) |
| Lecture - Class 2204 -Section 9 | Sunday<br>6:00PM to 7:00PM<hr>Wednesday<br>2:00PM to 4:00PM | 01.1.06<br>12.1.03 | Ridha Ben Rejeb<br>Ridha Ben Rejeb | open (111-120)<br>open (27-30) |
| Lecture - Class 2211 -Section 16 | Monday<br>12:00PM to 1:00PM<hr>Wednesday<br>2:00PM to 4:00PM | 01.1.06<br>12.2.10 | Irum Naz<br>Irum Naz | open (87-90)<br>open (29-30) |
| Lecture - Class 2212 -Section 17 | Monday<br>12:00PM to 1:00PM<hr>Tuesday<br>12:00PM to 2:00PM | 01.1.06<br>10.1.31 | Irum Naz<br>Irum Naz | open (87-90)<br>open (30-30) |
| Lecture - Class 2213 -Section 18 | Monday<br>12:00PM to 1:00PM<hr>Thursday<br>12:00PM to 2:00PM | 01.1.06<br>10.1.31 | Irum Naz<br>Irum Naz | open (87-90)<br>open (28-30) |
| Lecture - Class 2216 -Section 21 | Tuesday<br>2:00PM to 3:00PM<hr>Wednesday<br>2:00PM to 4:00PM | 01.1.06<br>05.1.66 | Cristina Fabretto<br>Cristina Fabretto | open (117-120)<br>open (30-30) |
| Lecture - Class 2217 -Section 22 | Tuesday<br>2:00PM to 3:00PM<hr>Monday<br>2:00PM to 4:00PM | 01.1.06<br>10.2.01 | Cristina Fabretto<br>Cristina Fabretto | open (117-120)<br>open (29-30) |
| Lecture - Class 2218 -Section 23 | Tuesday<br>2:00PM to 3:00PM<hr>Wednesday<br>4:00PM to 6:00PM | 01.1.06<br>05.1.38 | Cristina Fabretto<br>Cristina Fabretto | open (117-120)<br>open (28-30) |
| Lecture - Class 2220 -Section 25 | Monday<br>4:00PM to 5:00PM<hr>Tuesday<br>2:00PM to 4:00PM | 05.2.44<br>10.2.06 | Shawn Ramsey<br>Shawn Ramsey | open (53-58)<br>open (25-29) |
| Lecture - Class 2221 -Section 26 | Monday<br>4:00PM to 5:00PM<hr>Tuesday<br>4:00PM to 6:00PM | 05.2.44<br>10.2.06 | Shawn Ramsey<br>Shawn Ramsey | open (53-58)<br>open (28-29) |
| Lecture - Class 2227 -Section 32 | Tuesday<br>4:00PM to 5:00PM<hr>Thursday<br>2:00PM to 4:00PM | 12.1.08<br>12.1.03 | Irum Naz<br>Irum Naz | open (60-60)<br>open (30-30) |
| Lecture - Class 2228 -Section 33 | Tuesday<br>4:00PM to 5:00PM<hr>Wednesday<br>4:00PM to 6:00PM | 12.1.08<br>05.2.25 | Irum Naz<br>Irum Naz | open (60-60)<br>open (30-30) |

## PHYS1021 General Physics Lab

| Class ID | Days and Times | Room | Instructor | Status |
|----------|----------------|------|------------|--------|
| Laboratory - Class 2530 -Section 1 | Tuesday<br>8:00AM to 11:00AM | 05.1.06 | Fasna Olikkal | open (15-18) |
| Laboratory - Class 2533 -Section 4 | Tuesday<br>5:00PM to 8:00PM | 05.1.06 | Luka Tanasijin | open (13-18) |
| Laboratory - Class 2534 -Section 5 | Sunday<br>5:00PM to 8:00PM | 05.1.06 | Luka Tanasijin | open (14-18) |
| Laboratory - Class 2535 -Section 6 | Thursday<br>2:00PM to 5:00PM | 05.1.02 | Fasna Olikkal | open (6-18) |
| Laboratory - Class 2536 -Section 7 | Wednesday<br>2:00PM to 5:00PM | 05.1.06 | Fasna Olikkal | open (8-18) |
| Laboratory - Class 2537 -Section 8 | Monday<br>2:00PM to 5:00PM | 05.1.02 | Luka Tanasijin | open (6-18) |
| Laboratory - Class 2538 -Section 9 | Monday<br>10:00AM to 1:00PM | 05.1.02 | Fasna Olikkal | open (2-18) |
| Laboratory - Class 2539 -Section 10 | Wednesday<br>10:00AM to 1:00PM | 05.1.02 | Luka Tanasijin | open (8-18) |
| Laboratory - Class 2540 -Section 11 | Tuesday<br>2:00PM to 5:00PM | 05.1.02 | Luka Tanasijin<br>Luka Tanasijin | open (15-18) |
| Laboratory - Class 2541 -Section 12 | Tuesday<br>11:00AM to 2:00PM | 05.1.02 | Staff | open (16-18) |
| Laboratory - Class 2543 -Section 14 | Thursday<br>11:00AM to 2:00PM | 05.1.06 | Luka Tanasijin<br>Luka Tanasijin<br>Luka Tanasijin<br>Luka Tanasijin | open (16-18) |
| Laboratory - Class 2544 -Section 15 | Tuesday<br>2:00PM to 5:00PM | 05.1.06 | Fasna Olikkal | open (15-18) |
| Laboratory - Class 2545 -Section 16 | Sunday<br>11:00AM to 2:00PM | 05.1.02 | Fasna Olikkal | open (9-18) |
| Laboratory - Class 2547 -Section 18 | Sunday<br>8:00AM to 11:00AM | 05.1.06 | Staff | open (15-18) |
| Laboratory - Class 2548 -Section 19 | Thursday<br>8:00AM to 11:00AM | 05.1.02 | Fasna Olikkal | open (5-18) |
| Laboratory - Class 2551 -Section 22 | Sunday<br>2:00PM to 5:00PM | 05.1.02 | Fasna Olikkal<br>Fasna Olikkal<br>Fasna Olikkal | open (15-18) |
| Laboratory - Class 2556 -Section 27 | Sunday<br>2:00PM to 5:00PM | 05.1.06 | Luka Tanasijin<br>Luka Tanasijin<br>Luka Tanasijin | open (18-18) |

## AETN 1112 Digital Electronics

| Class ID                         | Days and Times                                     | Room                      | Instructor                          | Status       |
|----------------------------------|-----------------------------------------------------|---------------------------|-------------------------------------|--------------|
| Lecture - Class 1868 -Section 2 | Sunday<br>Tuesday<br>Thursday<br>12:00PM - 1:00PM <hr> | 05.2.37<br>05.2.37<br>05.2.37 | Staff<br>Staff<br>Staff               | open (30-30) |
| Lecture - Class 1869 -Section 3 | Sunday<br>Tuesday<br>Thursday<br>1:00PM - 2:00PM <hr>  | 05.2.55<br>05.2.55<br>05.2.55 | Ghufran Khalaf Ja'afreh<br>Ghufran Khalaf Ja'afreh<br>Ghufran Khalaf Ja'afreh | open (28-30) |
| Lecture - Class 1870 -Section 4 | Sunday<br>Tuesday<br>Thursday<br>12:00PM - 1:00PM <hr> | 05.2.25<br>05.2.25<br>05.2.25 | Ghufran Khalaf Ja'afreh<br>Ghufran Khalaf Ja'afreh<br>Ghufran Khalaf Ja'afreh | open (28-30) |

## AETN1212 Digital Electronics Lab:
| Class ID                         | Days and Times                                            | Room     | Instructor             | Status         | Rating |
|----------------------------------|------------------------------------------------------------|----------|------------------------|----------------|--------|
| Laboratory - Class 1880 -Section 1 | Wednesday<br>4:00PM to 6:00PM <hr>                        | 09.2.79  | Mariam Al-Ghanma       | open (15-15)   |        |
| Laboratory - Class 1881 -Section 2 | Wednesday<br>2:00PM to 4:00PM <hr>                        | 09.2.79  | Eithar Mustafa         | open (15-15)   |        |
| Laboratory - Class 1882 -Section 3 | Tuesday<br>2:00PM to 4:00PM <hr>                          | 09.2.79  | Eithar Mustafa         | open (15-15)   |        |
| Laboratory - Class 1883 -Section 4 | Monday<br>10:00AM to 12:00PM <hr>                         | 09.2.79  | Mariam Al-Ghanma       | open (15-15)   |        |
| Laboratory - Class 1884 -Section 5 | Thursday<br>6:00PM to 8:00PM <hr>                         | 08.1.03  | Alaa Elsaqa            | open (15-15)   |        |
| Laboratory - Class 1885 -Section 6 | Wednesday<br>11:00AM to 1:00PM <hr>                       | 09.2.79  | Alaa Elsaqa            | open (15-15)   |        |
| Laboratory - Class 1886 -Section 7 | Sunday<br>10:00AM to 12:00PM <hr>                         | 09.2.79  | Amira Mustapha         | open (15-15)   |        |
| Laboratory - Class 1887 -Section 8 | Tuesday<br>8:00AM to 10:00AM <hr>                         | 09.2.79  | Amira Mustapha         | open (15-15)   |        |
| Laboratory - Class 1888 -Section 9 | Thursday<br>12:00PM to 2:00PM <hr>                        | 09.2.79  | Mariam Al-Ghanma       | open (15-15)   |        |
| Laboratory - Class 1889 -Section 10| Sunday<br>12:00PM to 2:00PM <hr>                          | 09.1.41  | Alaa Elsaqa            | open (15-15)   |        |
| Laboratory - Class 1890 -Section 11| Wednesday<br>8:00AM to 10:00AM <hr>                       | 09.2.69  | Ghufran Khalaf Ja'afreh| open (15-15)   |        |

## AETN 1102 Network Fundamentals

| Class ID                         | Days and Times                                | Room                | Instructor         | Status         |
|----------------------------------|-----------------------------------------------|---------------------|--------------------|----------------|
| Lecture - Class 1863 -Section 2 | Sunday<br>Tuesday<br>Thursday<br>1:00PM - 2:00PM <hr> | 05.2.36<br>05.2.36<br>05.2.36 | Permjit Soora<br>Permjit Soora<br>Permjit Soora | open (25-30)   |
| Lecture - Class 1866 -Section 5 | Sunday<br>Tuesday<br>Thursday<br>3:00PM - 4:00PM <hr> | 05.2.25<br>05.2.25<br>05.2.25 | Nicolae Nechita<br>Nicolae Nechita<br>Nicolae Nechita | open (28-30)   |

## AETN 1202 Network Fundamentals Lab

| Class ID                          | Days and Times             | Room     | Instructor         | Status       |
|-----------------------------------|-----------------------------|----------|--------------------|--------------|
| Laboratory - Class 1873 -Section 1 | Wednesday<br>10:00AM - 1:00PM <hr> | 09.2.07 | Mariam Al-Ghanma   | open (18-20) |
| Laboratory - Class 1874 -Section 2 | Tuesday<br>2:00PM - 5:00PM <hr>    | 09.2.07 | Mariam Al-Ghanma   | open (20-20) |
| Laboratory - Class 1877 -Section 5 | Monday<br>10:00AM - 1:00PM <hr>    | 09.2.07 | Alaa Elsaqa        | open (19-20) |
| Laboratory - Class 1878 -Section 6 | Thursday<br>2:00PM - 5:00PM <hr>   | 09.2.07 | Alaa Elsaqa        | open (18-20) |

## MATH 2010 Calculus II 

| Class ID                             | Days and Times                                              | Room                    | Instructor     | Status         |
|--------------------------------------|--------------------------------------------------------------|-------------------------|----------------|----------------|
| LecTheatre - Class 2504 -Section 1 <br>Lecture - Class 2505 -Section 2 | Sunday<br>11:00AM - 12:30PM<br><hr>Tuesday<br>2:00PM - 3:30PM<br><hr> | 01.1.04<br>05.2.60       | Ramzan Ali<br>Ramzan Ali | open (40-90)<br>open (18-30) |
| LecTheatre - Class 2504 -Section 1 <br>Lecture - Class 2506 -Section 3 | Sunday<br>11:00AM - 12:30PM<br><hr>Tuesday<br>9:30AM - 11:00AM<br><hr> | 01.1.04<br>05.2.43       | Ramzan Ali<br>Ramzan Ali | open (40-90)<br>open (22-30) |
| LecTheatre - Class 2508 -Section 5 <br>Lecture - Class 2509 -Section 6 | Sunday<br>12:30PM - 2:00PM<br><hr>Wednesday<br>8:00AM - 9:30AM<br><hr> | 01.1.04<br>05.2.60       | Staff<br>Staff           | open (80-90)<br>open (29-30) |
| LecTheatre - Class 2508 -Section 5 <br>Lecture - Class 2510 -Section 7 | Sunday<br>12:30PM - 2:00PM<br><hr>Wednesday<br>2:00PM - 3:30PM<br><hr> | 01.1.04<br>05.2.36       | Staff<br>Staff           | open (80-90)<br>open (24-30) |
| LecTheatre - Class 2508 -Section 5 <br>Lecture - Class 2511 -Section 8 | Sunday<br>12:30PM - 2:00PM<br><hr>Wednesday<br>9:30AM - 11:00AM<br><hr> | 01.1.04<br>05.1.51       | Staff<br>Staff           | open (80-90)<br>open (27-30) |
| LecTheatre - Class 2512 -Section 9 <br>Lecture - Class 2513 -Section 10 | Sunday<br>5:00PM - 6:30PM<br><hr>Wednesday<br>5:00PM - 6:30PM<br><hr>  | 01.1.04<br>05.2.43       | Staff<br>Staff           | open (75-90)<br>open (15-30) |
| LecTheatre - Class 2504 -Section 1 <br>Lecture - Class 2507 -Section 4 | Sunday<br>11:00AM - 12:30PM<br><hr>Tuesday<br>11:00AM - 12:30PM<br><hr> | 01.1.04<br>05.2.24       | Ramzan Ali<br>Ramzan Ali | open (40-90)<br>closed       |
