---
title: "T1 Introduction to Digital System"
---

| Analog | Digital |
|---|---|
| Infinite number of values | Specific number of values |
| Continuous curve when analog values are plotted against time | Discontinuous values when analog values are plotted against time |
| Starts from zero to a specific value | 
| Intermediate values are guessed | A change in values occurs when a specified exact attribute change occurs |
| | Varies in descrete steps |

You convert analog to digital via sampling and then quantization:

- Sampling: Take samples of the analog signal at a specific resolution
- Quantisation: Convert samples to specific descrete levels
- Encoding: convert levels to completely digital signals as in zeroes and ones

## Binary Digital Signal

Only possible values are 0 and 1

## Logic Gates

- Very small device with inputs and outputs
- Contains resistors, capacitors, transistors, etc
- They are devices

### Families of Logic Gates

- TTL
- CMOS: 0 and 1 are the only inputs. 

## Physical Construction - DIP Packages

### How to number the pins of an IC

There is a circle on one side of the IC. With the circle on top, number the pins counter-clockwise. Generaly $7 = \mathrm{GND}$ and $14 = \mathrm{VCC}$

If you supply live voltage to GND, it will burn

### TTL:

- Logic 0: $0 - 0.8$
- Logic 1: $2 - 5$
- Invalid Region: $0.8 - 2$
- Supply of max voltage burns the gate

### CMOS:

- Logic 0: $0 - 0.6$
- Logic 1: $1 - 1.5$
- Invalid Region: $0.6 - 1$
- Supply of max voltage burns the gate

## Advantages of Digital Systems

## Limi

## Examples of ADC: Comparators


