---
title: "T3 Protocols and Reference Models"
---

## Data access

In IPv4:

In 192.168.1.110, 192.168.1 bits are the network part of the address while 110 is the host part of the address.

$\underbrace{192.168.1.110}_{\text{Network part of address}}  \underbrace{110}_\text{host}$

In a local network, the network of the address should not be differentbut the same. Only th ehost part changes.

Segement is encapsulate in Layer 3 info. This is encapsulated in layer 2 info.

### Data Link Addresses

Each port of a routeer has different MAC addresses

### Role of the Data Link Layer Addresses: Different IP Networks

IP address is used for end to end connection, while mac address is used for connectivity in a segment of a network

MAC Addresses are kept locally in local network. It's not visible from another network

- MAC Addresses are a layer 2 address
- IP Addresses are a layer 3 address

| MAC | IP |
|-|-|
| Layer 2 address | Layer 3 address |
| Local source to destination communication | Source to remote device communication |
